class Brackets{
	synchronized static public void generate(String threadCode) {
		for(int i = 1;i<=10;i++) {
			if(i<=5) {
				System.out.print("[");
			}
			else {
				System.out.print("]");
			}
		}
		System.out.println("Generated by thread "+threadCode);
	}
}

public class GenerateBrackets {
   
	public static void main(String[] args) throws InterruptedException {

		new Thread(new Runnable() {
			public void run() {
				for(int i = 1;i<=5;i++) {
					Brackets.generate("Thread1");
				}
				
			}
		}).start();
		
		new Thread(new Runnable() {
			public void run() {
				for(int i = 1;i<=5;i++) {
					Brackets.generate("Thread 2");
				}
				
			}
		}).start();
	}
	
}



	
